# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rails/all'
require 'rspec/rails'
require 'simple_breadcrumbs'

require 'coveralls'
Coveralls.wear!

ActiveSupport.on_load(:active_record) do
  include HasBreadcrumb
end

ActiveSupport.on_load(:action_controller) do
  include ActionView::Helpers
  include ShowBreadcrumb
end

I18n.enforce_available_locales = false

# Load support files
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].each {|f| require f}

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
end
